version: '3'
services:
  ds_landscape_web:
    # Путь до Dockerfile
    build: ./front
    # Создание переменных окружения в контейнере
    #environment:
    #  - BACK_URL=flask:5000
      ##
    # Перезапускаем сервис в случае падения 
    restart: on-failure
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend
    # volumes:
    #   - ./front:/front
    image: ds_landscape
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "8050:8050"
    command: python web.py